version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: 'db'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - fastapi_net
    ports:
      - 33306:3306
  app:
    restart: always
    build: .
    container_name: 'app'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    networks:
      - fastapi_net
    ports:
      - 8000:8000
volumes:
  mysql_data:
    name: 'mysql_data'
networks:
  fastapi_net:
    name: 'fastapi_net'
