version: '3'
services:
  db:
    image: postgres:15
    restart: always
    container_name: 'db'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'test'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_net
    ports:
      - 5432:5432
  app:
    image: fastapi-myapp:latest
    restart: always
    container_name: 'app'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_SERVER: 'db'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'test'
      DATABASE_URL: "mysql://root@db:3306/test?charset=utf8"
    tty: true
    networks:
      - fastapi_net
    ports:
      - 8000:8000
    depends_on:
      - 'db'
volumes:
  postgres_data:
    name: 'postgres_data'
networks:
  fastapi_net:
    name: 'fastapi_net'
